version: '3.8'

services:
  mongo:
    image: mongo:8.0-rc
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongodb-mongo-express
      - mongodb-moviesapi

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    networks:
      - mongodb-mongo-express

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      -  redis-moviesapi

  movies-api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017
      REDIS_URI: redis://redis:6379
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis
    networks:
      - mongodb-moviesapi
      - redis-moviesapi

networks:
  redis-moviesapi:
    driver: bridge
  mongodb-moviesapi:
    driver: bridge
  mongodb-mongo-express:
     driver: bridge